version: '3.8'

services:
  # Base de données MongoDB
  mongodb:
    image: mongo:4.4
    container_name: news-aggregator-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=news_aggregator
    restart: always
    networks:
      - app-network

  # Service d'administration MongoDB (optionnel mais pratique)
  mongo-express:
    image: mongo-express
    container_name: news-aggregator-mongo-express
    depends_on:
      - mongodb
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=devpassword
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_URL=mongodb://admin:password@mongodb:27017/
    restart: always
    networks:
      - app-network

# Définition des volumes persistants
volumes:
  mongodb_data:
    name: news-aggregator-mongodb-data

# Définition du réseau interne
networks:
  app-network:
    driver: bridge
