// Sources Tech & Numérique - Collection personnalisée

// Création de la collection Tech & Numérique
const techCollection = db.collections.insertOne({
  name: 'Tech & Numérique ',
  description: "Actu sur l'actu tech et les enjeux numériques",
  userId: webUser.insertedId,
  isPublic: true,
  createdAt: new Date(),
  updatedAt: new Date(),
});

print('Collection Tech & Numérique créée avec succès. ID: ' + techCollection.insertedId);

// Mise à jour de l'avatar de l'utilisateur
db.users.updateOne(
  { _id: webUser.insertedId },
  {
    $set: {
      avatar: 'https://www.alicepoggioli.fr/_astro/_alice-poggioli-comp.DDy5gSTJ_ZROOdi.webp',
      avatarType: 'url',
      defaultCollection: techCollection.insertedId,
    },
  }
);

// Insertion des sources
const sources = [
  {
    name: '404 Media',
    url: 'https://www.404media.co/',
    rssUrl: 'https://www.404media.co/rss/',
    faviconUrl: 'https://www.404media.co/favicon.ico',
    description:
      "Média indépendant américain spécialisé dans l'investigation technologique, la surveillance numérique et les dérives des plateformes.",
    funding: {
      type: 'independent',
      details: 'Média indépendant par abonnement',
    },
    orientations: ['tech-news', 'privacy', 'investigation'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Reflets.info',
    url: 'https://reflets.info/',
    rssUrl: 'https://reflets.info/feeds/public',
    faviconUrl: 'https://reflets.info/favicon.ico',
    description:
      'Média français indépendant traitant des enjeux numériques, de la surveillance, de la sécurité informatique et des libertés digitales.',
    funding: {
      type: 'independent',
      details: 'Média indépendant avec dons',
    },
    orientations: ['privacy', 'security', 'digital-rights'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Dans les algorithmes',
    url: 'https://danslesalgorithmes.net/',
    rssUrl: 'https://danslesalgorithmes.net/feed',
    faviconUrl: 'https://danslesalgorithmes.net/favicon.ico',
    description:
      "Blog français d'analyse critique des algorithmes, de l'IA et des enjeux sociétaux du numérique.",
    funding: {
      type: 'independent',
      details: 'Blog personnel indépendant',
    },
    orientations: ['artificial-intelligence', 'algorithms', 'digital-society'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Journal du Net',
    url: 'https://www.journaldunet.com/',
    rssUrl: 'https://www.journaldunet.com/rss.xml',
    faviconUrl: 'https://www.journaldunet.com/favicon.ico',
    description:
      "Média français de référence sur l'économie numérique, les technologies et l'innovation. Actualités business et tech.",
    funding: {
      type: 'private',
      details: 'Groupe CCM Benchmark',
    },
    orientations: ['tech-news', 'business', 'innovation'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Electronique Magazine',
    url: 'http://www.electronique-mag.com/',
    rssUrl: 'http://www.electronique-mag.com/backend.xml',
    faviconUrl: 'http://www.electronique-mag.com/favicon.ico',
    description:
      "Magazine français spécialisé dans l'électronique, les composants et les technologies embarquées.",
    funding: {
      type: 'private',
      details: 'Publication spécialisée',
    },
    orientations: ['electronics', 'hardware', 'technical'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Framablog',
    url: 'https://framablog.org/',
    rssUrl: 'https://framablog.org/feed/',
    faviconUrl: 'https://framablog.org/favicon.ico',
    description:
      'Blog de Framasoft, association française de promotion du logiciel libre et des alternatives numériques éthiques.',
    funding: {
      type: 'non-profit',
      details: 'Association Framasoft',
    },
    orientations: ['open-source', 'digital-rights', 'privacy'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Framasoft RSS',
    url: 'https://framasoft.org/',
    rssUrl: 'https://rss.framasoft.org',
    faviconUrl: 'https://framasoft.org/favicon.ico',
    description:
      'Flux RSS principal de Framasoft, réseau dédié à la promotion du libre et aux alternatives éthiques au numérique.',
    funding: {
      type: 'non-profit',
      details: 'Association Framasoft',
    },
    orientations: ['open-source', 'digital-rights', 'alternatives'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'FrenchWeb',
    url: 'https://www.frenchweb.fr/',
    rssUrl: 'https://www.frenchweb.fr/feed',
    faviconUrl: 'https://www.frenchweb.fr/favicon.ico',
    description:
      "Média français de référence sur l'écosystème startup, l'innovation et l'entrepreneuriat tech en France.",
    funding: {
      type: 'private',
      details: 'Média spécialisé startup',
    },
    orientations: ['startup', 'innovation', 'entrepreneurship'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Human Coders News',
    url: 'https://news.humancoders.com/',
    rssUrl: 'https://news.humancoders.com/items/feed.rss',
    faviconUrl: 'https://news.humancoders.com/favicon.ico',
    description:
      'Actualités techniques pour développeurs : programmation, outils, frameworks et bonnes pratiques du développement logiciel.',
    funding: {
      type: 'private',
      details: 'Human Coders (formation développeurs)',
    },
    orientations: ['programming', 'development', 'technical'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'IT-Connect',
    url: 'https://www.it-connect.fr/',
    rssUrl: 'https://www.it-connect.fr/feed/',
    faviconUrl: 'https://www.it-connect.fr/favicon.ico',
    description:
      'Blog français spécialisé en administration système, réseau, sécurité et infrastructure IT.',
    funding: {
      type: 'independent',
      details: 'Blog indépendant avec publicité',
    },
    orientations: ['system-admin', 'network', 'security'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Journal du Hacker',
    url: 'https://www.journalduhacker.net/',
    rssUrl: 'https://www.journalduhacker.net/rss',
    faviconUrl: 'https://www.journalduhacker.net/favicon.ico',
    description:
      "Agrégateur communautaire français d'actualités tech, programmation et culture hacker.",
    funding: {
      type: 'community',
      details: 'Communauté bénévole',
    },
    orientations: ['programming', 'hacker-culture', 'community'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'JustGeek',
    url: 'https://www.justgeek.fr/',
    rssUrl: 'https://www.justgeek.fr/feed/',
    faviconUrl: 'https://www.justgeek.fr/favicon.ico',
    description: 'Blog français sur les technologies, gadgets, applications et culture geek.',
    funding: {
      type: 'independent',
      details: 'Blog indépendant avec publicité',
    },
    orientations: ['tech-news', 'gadgets', 'geek-culture'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: "L'ADN",
    url: 'https://www.ladn.eu/',
    rssUrl: 'https://www.ladn.eu/feed',
    faviconUrl: 'https://www.ladn.eu/favicon.ico',
    description:
      "Média français sur l'innovation, les tendances digitales, la créativité et les nouveaux usages.",
    funding: {
      type: 'private',
      details: 'Groupe Monkey Media',
    },
    orientations: ['innovation', 'digital-trends', 'creativity'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'La Quadrature du Net',
    url: 'https://www.laquadrature.net/',
    rssUrl: 'https://www.laquadrature.net/feed/',
    faviconUrl: 'https://www.laquadrature.net/favicon.ico',
    description:
      'Association française de défense des droits et libertés des citoyens sur Internet. Analyses juridiques et techniques.',
    funding: {
      type: 'non-profit',
      details: 'Association avec dons',
    },
    orientations: ['digital-rights', 'privacy', 'law'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'La Revue du Digital',
    url: 'https://www.larevuedudigital.com/',
    rssUrl: 'https://www.larevuedudigital.com/feed/',
    faviconUrl: 'https://www.larevuedudigital.com/favicon.ico',
    description:
      "Média français sur la transformation digitale, les technologies émergentes et l'innovation numérique.",
    funding: {
      type: 'private',
      details: 'Média spécialisé digital',
    },
    orientations: ['digital-transformation', 'innovation', 'business'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Feedly - Nouvelles fonctionnalités',
    url: 'https://feedly.com/',
    rssUrl: 'https://feedly.com/new-features/feed.xml',
    faviconUrl: 'https://feedly.com/favicon.ico',
    description:
      'Annonces des nouvelles fonctionnalités de Feedly, lecteur RSS et outil de veille technologique.',
    funding: {
      type: 'private',
      details: 'Feedly Inc.',
    },
    orientations: ['tools', 'rss', 'productivity'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Mais où va le web',
    url: 'https://maisouvaleweb.fr/',
    rssUrl: 'https://maisouvaleweb.fr/feed/',
    faviconUrl: 'https://maisouvaleweb.fr/favicon.ico',
    description:
      "Blog français d'analyse critique du web, des réseaux sociaux et des enjeux du numérique.",
    funding: {
      type: 'independent',
      details: 'Blog personnel indépendant',
    },
    orientations: ['web-analysis', 'social-media', 'digital-society'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Gauthier Roussilhe',
    url: 'https://gauthierroussilhe.com/',
    rssUrl: 'https://gauthierroussilhe.com/feed',
    faviconUrl: 'https://gauthierroussilhe.com/favicon.ico',
    description:
      'Blog de Gauthier Roussilhe, designer et chercheur français spécialisé dans les enjeux environnementaux du numérique.',
    funding: {
      type: 'independent',
      details: 'Blog personnel de recherche',
    },
    orientations: ['sustainability', 'design', 'digital-ecology'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Mastodon Blog',
    url: 'https://blog.joinmastodon.org/',
    rssUrl: 'https://blog.joinmastodon.org/index.xml',
    faviconUrl: 'https://blog.joinmastodon.org/favicon.ico',
    description:
      'Blog officiel de Mastodon, réseau social décentralisé. Actualités sur le développement et la communauté.',
    funding: {
      type: 'non-profit',
      details: 'Mastodon gGmbH (organisation à but non lucratif)',
    },
    orientations: ['social-media', 'decentralization', 'open-source'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Next INpact Audio',
    url: 'https://next.ink/',
    rssUrl: 'https://next.ink/feed/mp3/',
    faviconUrl: 'https://next.ink/favicon.ico',
    description:
      "Flux podcast de Next INpact, média français indépendant spécialisé dans l'actualité tech et numérique.",
    funding: {
      type: 'independent',
      details: 'Média indépendant par abonnement',
    },
    orientations: ['tech-news', 'podcast', 'digital-rights'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Projets Libres',
    url: 'https://www.projets-libres.org/',
    rssUrl: 'https://www.projets-libres.org/feed/',
    faviconUrl: 'https://www.projets-libres.org/favicon.ico',
    description:
      'Actualités et découvertes de logiciels libres, projets open source et alternatives numériques éthiques.',
    funding: {
      type: 'independent',
      details: 'Blog indépendant bénévole',
    },
    orientations: ['open-source', 'free-software', 'alternatives'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Presse Citron',
    url: 'https://www.presse-citron.net/',
    rssUrl: 'https://www.presse-citron.net/feed/',
    faviconUrl: 'https://www.presse-citron.net/favicon.ico',
    description:
      'Média français sur les technologies, startups, applications mobiles et tendances numériques.',
    funding: {
      type: 'private',
      details: 'Groupe Reworld Media',
    },
    orientations: ['tech-news', 'mobile', 'startup'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Programmez!',
    url: 'https://www.programmez.com/',
    rssUrl: 'https://www.programmez.com/rss.xml',
    faviconUrl: 'https://www.programmez.com/favicon.ico',
    description:
      'Magazine français de développement logiciel : langages, frameworks, méthodologies et outils pour développeurs.',
    funding: {
      type: 'private',
      details: 'Magazine spécialisé développement',
    },
    orientations: ['programming', 'development', 'software-engineering'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'CNIL',
    url: 'https://www.cnil.fr/',
    rssUrl: 'https://www.cnil.fr/rss',
    faviconUrl: 'https://www.cnil.fr/favicon.ico',
    description:
      'Commission française de protection des données personnelles. Actualités légales et réglementaires sur la privacy.',
    funding: {
      type: 'public',
      details: 'Autorité administrative indépendante',
    },
    orientations: ['privacy', 'law', 'data-protection'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'April - Revue de presse',
    url: 'https://www.april.org/',
    rssUrl: 'https://www.april.org/revue-de-presse/feed',
    faviconUrl: 'https://www.april.org/favicon.ico',
    description: "Revue de presse de l'association April, pionnière du logiciel libre en France.",
    funding: {
      type: 'non-profit',
      details: 'Association April',
    },
    orientations: ['open-source', 'free-software', 'digital-rights'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Le Monde - Pixels',
    url: 'https://www.lemonde.fr/pixels/',
    rssUrl: 'https://www.lemonde.fr/pixels/rss_full.xml',
    faviconUrl: 'https://www.lemonde.fr/favicon.ico',
    description:
      "Section tech du Monde, couvrant l'actualité numérique, les jeux vidéo et les enjeux sociétaux du digital.",
    funding: {
      type: 'private',
      details: 'Groupe Le Monde',
    },
    orientations: ['tech-news', 'gaming', 'digital-society'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Siècle Digital',
    url: 'https://siecledigital.fr/',
    rssUrl: 'https://siecledigital.fr/feed/',
    faviconUrl: 'https://siecledigital.fr/favicon.ico',
    description:
      "Média français sur la transformation digitale, les réseaux sociaux, l'e-commerce et les nouvelles technologies.",
    funding: {
      type: 'private',
      details: 'Média spécialisé digital',
    },
    orientations: ['digital-transformation', 'social-media', 'e-commerce'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'TechCrunch',
    url: 'https://techcrunch.com/',
    rssUrl: 'https://techcrunch.com/feed/',
    faviconUrl: 'https://techcrunch.com/favicon.ico',
    description:
      "Média américain de référence sur les startups, l'innovation technologique et l'écosystème entrepreneurial.",
    funding: {
      type: 'private',
      details: 'Verizon Media (Yahoo)',
    },
    orientations: ['startup', 'venture-capital', 'innovation'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Diplomatie France - Numérique',
    url: 'https://www.diplomatie.gouv.fr/',
    rssUrl: 'https://www.diplomatie.gouv.fr/spip.php?page=backend&id_rubrique=20158',
    faviconUrl: 'https://www.diplomatie.gouv.fr/favicon.ico',
    description:
      "Actualités diplomatiques françaises sur les enjeux numériques internationaux et la gouvernance d'Internet.",
    funding: {
      type: 'public',
      details: 'Ministère des Affaires étrangères',
    },
    orientations: ['digital-policy', 'international', 'governance'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'The Information',
    url: 'https://www.theinformation.com/',
    rssUrl: 'https://www.theinformation.com/feed',
    faviconUrl: 'https://www.theinformation.com/favicon.ico',
    description:
      "Média américain premium d'investigation technologique, couvrant les coulisses de la Silicon Valley et des grandes tech.",
    funding: {
      type: 'independent',
      details: 'Média indépendant par abonnement',
    },
    orientations: ['tech-investigation', 'silicon-valley', 'business'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Le Monde Informatique',
    url: 'https://www.lemondeinformatique.fr/',
    rssUrl: 'https://www.lemondeinformatique.fr/flux-rss//rss.xml',
    faviconUrl: 'https://www.lemondeinformatique.fr/favicon.ico',
    description:
      "Média français de référence pour les professionnels IT : actualités techniques, infrastructure et solutions d'entreprise.",
    funding: {
      type: 'private',
      details: 'Groupe IDG Communications',
    },
    orientations: ['enterprise-it', 'infrastructure', 'professional'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Wired',
    url: 'https://www.wired.com/',
    rssUrl: 'https://www.wired.com/feed/rss',
    faviconUrl: 'https://www.wired.com/favicon.ico',
    description:
      "Magazine américain iconique couvrant l'impact culturel et sociétal de la technologie, avec des analyses approfondies.",
    funding: {
      type: 'private',
      details: 'Condé Nast',
    },
    orientations: ['tech-culture', 'society', 'innovation'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'ZDNet France',
    url: 'https://www.zdnet.fr/',
    rssUrl: 'https://www.zdnet.fr/feeds/rss/actualites/?l=20',
    faviconUrl: 'https://www.zdnet.fr/favicon.ico',
    description:
      'Actualités technologiques et professionnelles françaises : entreprise, sécurité, cloud et transformation digitale.',
    funding: {
      type: 'private',
      details: 'Red Ventures',
    },
    orientations: ['enterprise', 'security', 'cloud'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'S.I.Lex',
    url: 'https://scinfolex.com/',
    rssUrl: 'https://scinfolex.com/feed/',
    faviconUrl: 'https://scinfolex.com/favicon.ico',
    description:
      "Blog de Lionel Maurel sur le droit de l'information, les biens communs numériques et les enjeux juridiques du web.",
    funding: {
      type: 'independent',
      details: 'Blog personnel de recherche',
    },
    orientations: ['digital-law', 'commons', 'copyright'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Korben',
    url: 'https://korben.info/',
    rssUrl: 'https://korben.info/feed',
    faviconUrl: 'https://korben.info/favicon.ico',
    description:
      'Blog français iconique de Korben, couvrant les outils, astuces, sécurité et découvertes du monde numérique.',
    funding: {
      type: 'independent',
      details: 'Blog indépendant avec publicité',
    },
    orientations: ['tools', 'security', 'tips-tricks'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Mouton Numérique',
    url: 'https://mouton-numerique.org/',
    rssUrl: 'https://mouton-numerique.org/feed/',
    faviconUrl: 'https://mouton-numerique.org/favicon.ico',
    description:
      'Blog français sur la protection de la vie privée, la sécurité numérique et les alternatives aux GAFAM.',
    funding: {
      type: 'independent',
      details: 'Blog indépendant bénévole',
    },
    orientations: ['privacy', 'security', 'alternatives'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Technopolice',
    url: 'https://technopolice.fr/',
    rssUrl: 'https://technopolice.fr/feed/',
    faviconUrl: 'https://technopolice.fr/favicon.ico',
    description:
      'Observatoire français des technologies de sécurité et de surveillance, analysant la technopolice.',
    funding: {
      type: 'non-profit',
      details: 'Projet associatif indépendant',
    },
    orientations: ['surveillance', 'security-tech', 'civil-rights'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Korben (YouTube)',
    url: 'https://www.youtube.com/channel/UCjCeyHQarZ0gtndcuz4dEkw',
    rssUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCjCeyHQarZ0gtndcuz4dEkw',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    description:
      "Chaîne YouTube de Korben : tutoriels, tests d'outils, sécurité informatique et culture geek.",
    funding: {
      type: 'independent',
      details: 'YouTube, sponsors',
    },
    orientations: ['tutorials', 'tools', 'security'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Underscore_ (YouTube)',
    url: 'https://www.youtube.com/channel/UCWedHS9qKebauVIK2J7383g',
    rssUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCWedHS9qKebauVIK2J7383g',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    description:
      "Chaîne YouTube française de vulgarisation technologique, couvrant l'actualité tech et les innovations.",
    funding: {
      type: 'independent',
      details: 'YouTube, sponsors',
    },
    orientations: ['tech-education', 'innovation', 'vulgarization'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Deus Ex Silicium (YouTube)',
    url: 'https://www.youtube.com/channel/UCH6ppHEvV3_WIXEwmhv9HEg',
    rssUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCH6ppHEvV3_WIXEwmhv9HEg',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    description:
      "Chaîne YouTube française sur l'informatique, l'électronique et les technologies avec un regard critique.",
    funding: {
      type: 'independent',
      details: 'YouTube, sponsors',
    },
    orientations: ['electronics', 'computing', 'critical-analysis'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Benjamin Code (YouTube)',
    url: 'https://www.youtube.com/channel/UCLOAPb7ATQUs_nDs9ViLcMw',
    rssUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCLOAPb7ATQUs_nDs9ViLcMw',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    description:
      'Chaîne YouTube française de programmation : tutoriels de développement, langages et bonnes pratiques.',
    funding: {
      type: 'independent',
      details: 'YouTube, sponsors',
    },
    orientations: ['programming', 'tutorials', 'development'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
  {
    name: 'Visio IA (YouTube)',
    url: 'https://www.youtube.com/channel/UCyc03X3uRuxM9n7fyRH_gIw',
    rssUrl: 'https://www.youtube.com/feeds/videos.xml?channel_id=UCyc03X3uRuxM9n7fyRH_gIw',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    description:
      "Chaîne YouTube française spécialisée dans l'intelligence artificielle : actualités, outils et vulgarisation IA.",
    funding: {
      type: 'independent',
      details: 'YouTube, sponsors',
    },
    orientations: ['artificial-intelligence', 'ai-tools', 'education'],
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date('2024-12-25'),
    collectionId: techCollection.insertedId,
    createdBy: webUser.insertedId,
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
    status: 'active',
  },
];

// Insertion des sources et récupération de leurs IDs
const insertedSources = db.sources.insertMany(sources);

// Mise à jour de la collection avec les références des sources
db.collections.updateOne(
  { _id: techCollection.insertedId },
  {
    $set: {
      sources: Object.values(insertedSources.insertedIds),
      updatedAt: new Date(),
    },
  }
);

print('Sources Tech & Numérique ajoutées à la collection avec succès.');
print('Nombre de sources ajoutées: ' + sources.length);
