// Script d'initialisation de la base de données MongoDB
// À placer dans un dossier 'mongo-init' à la racine du projet
db = db.getSiblingDB('news_aggregator');

// Création des collections
db.createCollection('sources');
db.createCollection('articles');
db.createCollection('users');
db.createCollection('analytics');

// Ajout des sources préconfigurées
db.sources.insertMany([
  {
    name: 'Le Monde',
    url: 'https://www.lemonde.fr',
    rssUrl: 'https://www.lemonde.fr/rss/une.xml',
    faviconUrl: 'https://www.lemonde.fr/favicon.ico',
    categories: ['politique', 'économie', 'international'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Le Figaro',
    url: 'https://www.lefigaro.fr',
    rssUrl: 'https://www.lefigaro.fr/rss/figaro_actualites.xml',
    faviconUrl: 'https://www.lefigaro.fr/favicon.ico',
    categories: ['politique', 'économie', 'société'],
    orientation: {
      political: 'droite',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Libération',
    url: 'https://www.liberation.fr',
    rssUrl: 'https://www.liberation.fr/rss/',
    faviconUrl: 'https://www.liberation.fr/favicon.ico',
    categories: ['politique', 'société', 'culture'],
    orientation: {
      political: 'gauche',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  // Sources supplémentaires
  {
    name: 'Les Echos',
    url: 'https://www.lesechos.fr',
    rssUrl: 'https://services.lesechos.fr/rss/les-echos-actualites.xml',
    faviconUrl: 'https://www.lesechos.fr/favicon.ico',
    categories: ['économie', 'finance', 'entreprises', 'marchés'],
    orientation: {
      political: 'centre-droit',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'France Info',
    url: 'https://www.francetvinfo.fr',
    rssUrl: 'https://www.francetvinfo.fr/titres.rss',
    faviconUrl: 'https://www.francetvinfo.fr/favicon.ico',
    categories: ['actualité', 'politique', 'société', 'international'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Le Point',
    url: 'https://www.lepoint.fr',
    rssUrl: 'https://www.lepoint.fr/rss.xml',
    faviconUrl: 'https://www.lepoint.fr/favicon.ico',
    categories: ['politique', 'économie', 'culture', 'société'],
    orientation: {
      political: 'centre-droit',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "L'Express",
    url: 'https://www.lexpress.fr',
    rssUrl: 'https://www.lexpress.fr/rss/alaune.xml',
    faviconUrl: 'https://www.lexpress.fr/favicon.ico',
    categories: ['politique', 'économie', 'société', 'international'],
    orientation: {
      political: 'centre-droit',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Mediapart',
    url: 'https://www.mediapart.fr',
    rssUrl: 'https://www.mediapart.fr/articles/feed',
    faviconUrl: 'https://www.mediapart.fr/favicon.ico',
    categories: ['politique', 'enquête', 'justice', 'société'],
    orientation: {
      political: 'gauche',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Le Parisien',
    url: 'https://www.leparisien.fr',
    rssUrl: 'https://feeds.leparisien.fr/leparisien/rss',
    faviconUrl: 'https://www.leparisien.fr/favicon.ico',
    categories: ['actualité', 'société', 'faits divers', 'local'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: '20 Minutes',
    url: 'https://www.20minutes.fr',
    rssUrl: 'https://www.20minutes.fr/feeds/rss-une.xml',
    faviconUrl: 'https://www.20minutes.fr/favicon.ico',
    categories: ['actualité', 'société', 'culture', 'sport'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "L'Humanité",
    url: 'https://www.humanite.fr',
    rssUrl: 'https://www.humanite.fr/rss/une.xml',
    faviconUrl: 'https://www.humanite.fr/favicon.ico',
    categories: ['politique', 'social', 'société', 'international'],
    orientation: {
      political: 'gauche',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Challenges',
    url: 'https://www.challenges.fr',
    rssUrl: 'https://www.challenges.fr/rss.xml',
    faviconUrl: 'https://www.challenges.fr/favicon.ico',
    categories: ['économie', 'entreprises', 'finance', 'innovation'],
    orientation: {
      political: 'centre-droit',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'La Croix',
    url: 'https://www.la-croix.com',
    rssUrl: 'https://www.la-croix.com/RSS/UNIVERS',
    faviconUrl: 'https://www.la-croix.com/favicon.ico',
    categories: ['actualité', 'religion', 'société', 'international'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Marianne',
    url: 'https://www.marianne.net',
    rssUrl: 'https://www.marianne.net/rss.xml',
    faviconUrl: 'https://www.marianne.net/favicon.ico',
    categories: ['politique', 'société', 'débats', 'culture'],
    orientation: {
      political: 'républicain',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Le Nouvel Obs',
    url: 'https://www.nouvelobs.com',
    rssUrl: 'https://www.nouvelobs.com/a-la-une/rss.xml',
    faviconUrl: 'https://www.nouvelobs.com/favicon.ico',
    categories: ['politique', 'culture', 'société', 'international'],
    orientation: {
      political: 'centre-gauche',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Les Inrockuptibles',
    url: 'https://www.lesinrocks.com',
    rssUrl: 'https://www.lesinrocks.com/feed/',
    faviconUrl: 'https://www.lesinrocks.com/favicon.ico',
    categories: ['culture', 'musique', 'cinéma', 'société'],
    orientation: {
      political: 'gauche',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: 'Courrier International',
    url: 'https://www.courrierinternational.com',
    rssUrl: 'https://www.courrierinternational.com/feed/all/rss.xml',
    faviconUrl: 'https://www.courrierinternational.com/favicon.ico',
    categories: ['international', 'géopolitique', 'monde', 'culture'],
    orientation: {
      political: 'centre',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
  {
    name: "L'Opinion",
    url: 'https://www.lopinion.fr',
    rssUrl: 'https://www.lopinion.fr/rss',
    faviconUrl: 'https://www.lopinion.fr/favicon.ico',
    categories: ['économie', 'politique', 'entreprises', 'finance'],
    orientation: {
      political: 'droite',
    },
    defaultEnabled: true,
    isUserAdded: false,
    addedDate: new Date(),
    fetchStatus: {
      success: true,
      message: '',
      timestamp: new Date(),
    },
    lastFetched: new Date(),
    updatedAt: new Date(),
  },
]);

// Création des index pour optimiser les requêtes
db.sources.createIndex({ name: 1 }, { unique: true });
db.articles.createIndex({ link: 1 }, { unique: true });
db.articles.createIndex({ publishedAt: -1 });
db.articles.createIndex({ sourceId: 1 });
db.users.createIndex({ email: 1 }, { unique: true });
